import json
import os
import re
import statistics

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LLM_SIGNAL_SYSTEM_PROMPT = """You are a text provenance analyst. Given a piece of text, assess whether it was likely written by a human or generated by an AI language model.

Consider things like: generic or repetitive phrasing, overly uniform sentence structure, common AI-generated stock phrases (e.g. "in today's digital age", "increasingly important part of"), lack of personal voice or specific detail, and overall naturalness of the writing.

Respond with ONLY a JSON object in this exact format, no other text:
{
  "llm_score": <float between 0 and 1, where 0 means very likely human-written and 1 means very likely AI-generated>,
  "reasoning": "<one or two sentence explanation of the score>"
}
"""


def get_llm_signal(text):
    """Send text to the Groq API and return a structured AI-vs-human assessment."""
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": LLM_SIGNAL_SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0,
        response_format={"type": "json_object"},
    )

    result = json.loads(response.choices[0].message.content)

    return {
        "llm_score": float(result["llm_score"]),
        "reasoning": result.get("reasoning", ""),
    }


PUNCTUATION_CHARS = ".,!?;:-—"


def _sentence_variation_score(sentences):
    """Low variation in sentence length (in words) looks more AI-like."""
    lengths = [len(s.split()) for s in sentences if s.strip()]
    if len(lengths) < 2:
        return 0.5

    mean_length = statistics.mean(lengths)
    if mean_length == 0:
        return 0.5

    stdev = statistics.stdev(lengths)
    coefficient_of_variation = stdev / mean_length
    return max(0.0, min(1.0, 1 - coefficient_of_variation))


def _vocabulary_diversity_score(words):
    """Low type-token ratio (repeated words) looks more AI-like."""
    if not words:
        return 0.5

    type_token_ratio = len(set(words)) / len(words)
    return max(0.0, min(1.0, 1 - type_token_ratio))


def _punctuation_uniformity_score(text):
    """Little punctuation variety (mostly periods) looks more AI-like."""
    used = {ch for ch in text if ch in PUNCTUATION_CHARS}
    diversity = len(used) / len(PUNCTUATION_CHARS)
    return max(0.0, min(1.0, 1 - diversity))


def _repetition_score(words):
    """A high ratio of repeated 3-word phrases looks more AI-like."""
    if len(words) < 3:
        return 0.5

    trigrams = [tuple(words[i:i + 3]) for i in range(len(words) - 2)]
    unique_trigrams = len(set(trigrams))
    return max(0.0, min(1.0, 1 - (unique_trigrams / len(trigrams))))


COMPONENT_WEIGHTS = {
    "sentence_variation": 0.36,
    "repetition": 0.28,
    "punctuation_uniformity": 0.18,
    "vocabulary_diversity": 0.18,
}

# Below this many words, vocabulary diversity and repetition don't have enough
# text to show real signal (almost any short passage has high TTR and no
# repeated trigrams). Scores on short text get pulled toward neutral (0.5)
# in proportion to how far below this threshold they fall.
MIN_RELIABLE_WORD_COUNT = 60


def get_heuristic_signal(text):
    """Measure structural and lexical writing patterns and return an AI-vs-human assessment."""
    sentences = [s for s in re.split(r"(?<=[.!?])\s+", text.strip()) if s]
    words = [w.lower() for w in re.findall(r"[a-zA-Z']+", text)]

    components = {
        "sentence_variation": _sentence_variation_score(sentences),
        "vocabulary_diversity": _vocabulary_diversity_score(words),
        "punctuation_uniformity": _punctuation_uniformity_score(text),
        "repetition": _repetition_score(words),
    }

    raw_score = sum(components[name] * weight for name, weight in COMPONENT_WEIGHTS.items())

    length_confidence = min(1.0, len(words) / MIN_RELIABLE_WORD_COUNT)
    heuristic_score = 0.5 + (raw_score - 0.5) * length_confidence

    return {
        "heuristic_score": heuristic_score,
        "components": components,
        "length_confidence": length_confidence,
    }
